version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
  - package-ecosystem: "gomod"
    directory: "/cmd/keeper"
    schedule:
      interval: "weekly"
    target-branch: "develop"