version: '3.6'
services:
  bsc:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["--http.addr", "0.0.0.0", "--ws.addr", "0.0.0.0"]
    environment:
      - LOG_LEVEL=3
      - DIFF_SYNC=true
      - CACHE=4096
    restart: unless-stopped
    ports:
      - 30311:30311
      - 6060:6060
      - 8545:8545
      - 8546:8546
    healthcheck:
      test: netstat -tunlp | grep 8545 > /dev/null; if [ 0 != $$? ]; then exit 1; else exit 0; fi;
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 3s