version: '3.6'
services:
  init:
    image: alpine
    command:
      - /bin/sh
      - -c
      - |
        chown -R 1000:1000 /data

        echo "done grany data directory permission"
    volumes:
      - data:/data

  bsc:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["--http.addr", "0.0.0.0", "--http.port", "8545", "--http.vhosts", "*", "--verbosity", "3"]
    environment:
      - BSC_NETWORK=mainnet
    restart: unless-stopped
    ports:
      - 30311:30311
      - 6060:6060
      - 8545:8545
      - 8546:8546
    healthcheck:
      test: netstat -tunlp | grep 8545 > /dev/null; if [ 0 != $$? ]; then exit 1; else exit 0; fi;
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 3s
    volumes:
      - data:/data

volumes:
  data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/tmp/bsc/data'