// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: internal/ethapi/mevpb/mev.proto

package mevpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BidBlockService_SendBidBlock_FullMethodName = "/mev.v1.BidBlockService/SendBidBlock"
)

// BidBlockServiceClient is the client API for BidBlockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BidBlockService accepts BEP-675 BidBlock submissions over gRPC.
// Other MEV APIs remain on JSON-RPC.
type BidBlockServiceClient interface {
	SendBidBlock(ctx context.Context, in *BidBlockRequest, opts ...grpc.CallOption) (*BidBlockResponse, error)
}

type bidBlockServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBidBlockServiceClient(cc grpc.ClientConnInterface) BidBlockServiceClient {
	return &bidBlockServiceClient{cc}
}

func (c *bidBlockServiceClient) SendBidBlock(ctx context.Context, in *BidBlockRequest, opts ...grpc.CallOption) (*BidBlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BidBlockResponse)
	err := c.cc.Invoke(ctx, BidBlockService_SendBidBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BidBlockServiceServer is the server API for BidBlockService service.
// All implementations must embed UnimplementedBidBlockServiceServer
// for forward compatibility.
//
// BidBlockService accepts BEP-675 BidBlock submissions over gRPC.
// Other MEV APIs remain on JSON-RPC.
type BidBlockServiceServer interface {
	SendBidBlock(context.Context, *BidBlockRequest) (*BidBlockResponse, error)
	mustEmbedUnimplementedBidBlockServiceServer()
}

// UnimplementedBidBlockServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBidBlockServiceServer struct{}

func (UnimplementedBidBlockServiceServer) SendBidBlock(context.Context, *BidBlockRequest) (*BidBlockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendBidBlock not implemented")
}
func (UnimplementedBidBlockServiceServer) mustEmbedUnimplementedBidBlockServiceServer() {}
func (UnimplementedBidBlockServiceServer) testEmbeddedByValue()                         {}

// UnsafeBidBlockServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BidBlockServiceServer will
// result in compilation errors.
type UnsafeBidBlockServiceServer interface {
	mustEmbedUnimplementedBidBlockServiceServer()
}

func RegisterBidBlockServiceServer(s grpc.ServiceRegistrar, srv BidBlockServiceServer) {
	// If the following call panics, it indicates UnimplementedBidBlockServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BidBlockService_ServiceDesc, srv)
}

func _BidBlockService_SendBidBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BidBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BidBlockServiceServer).SendBidBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BidBlockService_SendBidBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BidBlockServiceServer).SendBidBlock(ctx, req.(*BidBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BidBlockService_ServiceDesc is the grpc.ServiceDesc for BidBlockService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BidBlockService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mev.v1.BidBlockService",
	HandlerType: (*BidBlockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendBidBlock",
			Handler:    _BidBlockService_SendBidBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/ethapi/mevpb/mev.proto",
}
